"""Shared PySide6 UI components for droplet desktop applications."""

from dropletui.app import apply_app_theme, create_app, resolved_ui_font
from dropletui.containers import (
    DropletSplitter,
    bottom_split_view,
    form_panel,
    hbox,
    horizontal_splitter,
    section,
    separator,
    side_panel,
    split_view,
    splitter,
    toolbar,
    vbox,
    vertical_splitter,
)
from dropletui.controls import (
    DropletSlider,
    apply_button_style,
    button,
    check_box,
    combo_box,
    double_box,
    int_box,
    line_edit,
    slider,
    stage_button,
)
from dropletui.status import metric_readout, status_label
from dropletui.theme import Theme, configure_monospace_font, configure_pyqtgraph, stylesheet

__all__ = [
    "Theme",
    "apply_app_theme",
    "apply_button_style",
    "bottom_split_view",
    "button",
    "check_box",
    "combo_box",
    "configure_monospace_font",
    "configure_pyqtgraph",
    "create_app",
    "double_box",
    "DropletSplitter",
    "DropletSlider",
    "form_panel",
    "hbox",
    "horizontal_splitter",
    "int_box",
    "line_edit",
    "metric_readout",
    "resolved_ui_font",
    "section",
    "separator",
    "side_panel",
    "slider",
    "split_view",
    "splitter",
    "stage_button",
    "status_label",
    "stylesheet",
    "toolbar",
    "vbox",
    "vertical_splitter",
]
